### ISSUE TITLE
Bug with deleting requests and libraries/samples

### ISSUE THREAD

**Issue by nicolazilio** [maxplanck-ie/parkour2#25]
Hi @adRn-s ,

Deleting requests and libraries/samples doesn't work at all due to bugs in both the front end and back end. I tried to solve the issue like so https://github.com/maxplanck-ie/parkour2/commit/383b592cc30107a24edafce817b73792dad85c9e.

Maybe it would be usefult to have a discussion about until what stage a request/library/sample can be deleted?

Nicola

**Comment by adRn-s** [comment]
TBH, we didn't delete any data at all. Never. I believe this is a behaviour that was imposed upon our users since the early Django days (e.g. `on_delete` was undefined for foreign keys, so cascading effects were probably running wild and free).

Regarding stages, I'm rather inclined to think conservatively. That is, request are only allowed to be deleted before they are confirmed by PI (`status>=1`). One could stretch this a bit, and get into the quality check... so that even after this stage the requests are deletable (`status>=2`). Surely, we don't want users being able to delete requests that are already in the Pooling o Sequencing steps. Of course, in such scenarios if the decision is made, and it's critical to stop the procedure, users would have other means (e.g. telephone) to stop their request.

Anyway, what did you have in mind?

Implementing this fix should also take into account that in the future we'd like to have sequencing requests that are both 'duplicable' and 'movable' from one stage to the one before. The possibility to move requests backwards was explicitly mentioned as an important feature request by the sequencing facility over here. Specially during the Index Generator, Preparation, Pooling, and Loading of Flowcells.

**Comment by nicolazilio** [comment]
I agree with not deleting anything ever :) (but then I would ask why was the 'Delete' button added, if you don't want something to be deleted), but I think there are cases when deleting makes sense, for example, I didn't get enough DNA for one of my samples and therefore I would like to remove it from the request. 

I think a reasonable compromise would be that somebody can delete requests/libraries/samples up until submission, after that they shouldn't be allowed to be deleted. What do you think?

**Comment by adRn-s** [comment]
Agreed, requests deletion should only be allowed early on.
